# Generated by Django 3.0.4 on 2020-03-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networkros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, verbose_name='设备归属者')),
                ('address', models.CharField(max_length=50, verbose_name='设备管理地址')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '用户设备对应关系',
                'verbose_name_plural': '用户设备对应关系',
                'db_table': 'DeviceManage',
            },
        ),
    ]
