# Generated by Django 2.2 on 2020-03-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmanage',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='ip地址'),
        ),
    ]
