# Generated by Django 2.2 on 2020-03-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20200327_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmanage',
            name='ip',
            field=models.CharField(default='', max_length=60, verbose_name='ip地址'),
        ),
    ]
