# Generated by Django 2.2 on 2020-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20200327_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l2tp',
            name='status',
            field=models.BooleanField(default=False, verbose_name='VPN状态'),
        ),
    ]
